### ISSUE TITLE
Investigate and fix protobuf performance

### ISSUE THREAD

**Issue by anderslogg** [dtcc-platform/dtcc-io#21]
Read/write seems to be slow, should be orders of magnitude faster than JSON.

**Comment by dwastberg** [comment]
For reference. Reading in the 'raw' protobuf, ie 

`proto.City.FromString(pb_file.read_bytes())`

is very fast. The slow parts come after that

**Comment by anderslogg** [comment]
Things to try:

1. Can we beat JSON by a factor 10-100x for a simple enough data structure?
2. Keep adding complexity to it and see if/when it starts to become slow.
3. Are we using the correct flags to the pb compiler?
4. Are there any optimization flags we are not using?
5. Are there some directives or options we should set in the .proto file?

**Comment by dwastberg** [comment]
Problem was due to old version of protobuf not using the C extensions, but rather using the pure python fallback path. Updating to latest protobuf seems to fix the problem
